[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
no_match_test = "FFI"
ffi = true

[profile.ffi]
ffi = true
match_test = "FFI"
no_match_test = "a^"
fuzz_runs = 1000

[invariant]
runs = 100
depth = 25
fail_on_revert = true
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config